--- # A playbook to provision Jenkins server on Ubuntu 16.04
- hosts: all
  gather_facts: no

  vars:
    ufwports:
      - 22 # TO allow SSH
      - 8080 # For Jenkins
    packages:
      - gcc
      - git
      - git-core
      - python-dev
      - python-mysqldb
      - libmysqlclient-dev
      - python-setuptools
      - mysql-server
      - oracle-java8-installer
      - oracle-java8-set-default
      - maven
      - python-software-properties

  vars_prompt:
    - name: username
      prompt: "Enter remote username"
      private: no
    - name: jenkinspassword
      prompt: "Enter Jenkins Admin Password"
      private: yes

  tasks:
    - name: Installing python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

    - name: gather facts
      setup:

    - name: Adding the Jenkins Public GPG key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins-ci.org.key 
        state: present
      become: yes

    - name: Adding Jenkins to trusted sources.list
      apt_repository: 
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present
        update_cache: yes
      become: yes

    - name: Installing Jenkins
      apt: pkg=jenkins state=present update_cache=yes
      become: yes

    - name: Starting Jenkins service
      service:
        name: jenkins
        state: started
      become: yes

    - name: Add Oracle java apt repository key
      apt_repository:
        repo: 'ppa:webupd8team/java'
      become: yes

    - name: Accept Oracle java license
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
      changed_when: false
      become: yes

    - name: Installing required packages
      apt: pkg={{packages}} state=present
      become: yes

    - name: removing case sensitivity in Sql
      blockinfile:
        dest: /etc/mysql/my.cnf
        block: |
          [mysqld]
          lower_case_table_names = 1
      register: mysql_case_sensitivity
      become: yes

    - name: flush priviliges mysql root user
      shell: >
        mysql -u root --execute "UPDATE mysql.user SET plugin = 'mysql_native_password' WHERE user = 'root'; FLUSH PRIVILEGES;"
      become: yes

    - name: restart
      service: name=mysql state=restarted
      become: yes


    - name: Install Uncomplicated Firewall
      apt: pkg=ufw state=present update_cache=yes
      become: yes

    - name: Open port 8080
      ufw:
        rule: allow
        port: "{{ item }}"
      with_items:
        - "{{ ufwports }}"
      become: yes

    - name: Enable ufw
      ufw:
        state: enabled
        policy: deny
      become: yes

    - name: Get the jenkins-cli jarfile from the Jenkins server.
      get_url:
        url: "http://localhost:8080/jnlpJars/jenkins-cli.jar"
        dest: /home/
      register: jarfile_get
      until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
      retries: 5
      delay: 10
      check_mode: no
      become: yes

    - name: Getting Initial admin password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkinsadminpass
      become: yes

    - name: Adding mentioned user to jenkins
      shell: echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount("{{username}}", "{{jenkinspassword}}")' | java -jar /home/jenkins-cli.jar -auth admin:"{{jenkinsadminpass.stdout}}" -s http://localhost:8080/ groovy =

    - name: Installing Recommended Plugins
      shell: java -jar /home/jenkins-cli.jar -auth "{{username}}":"{{jenkinspassword}}" -s http://localhost:8080 install-plugin "{{item}}" -deploy
      with_items:
        - junit
        - postbuild-task
        - jacoco
        - test-stability
        - git
        - git-client
        - git-server
     
    - name: Turn off Jenkins setup wizard
      lineinfile:
          dest: /etc/default/jenkins
          regexp: '^JAVA_ARGS='
          line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
          insertbefore: '^DAEMON_ARGS='
      notify: restart jenkins
      become: yes

    - name: Enabling mysql to run on boot
      service:
        name: mysql
        state: started
        enabled: true
      become: yes

    - name: Sending template for iTrust to Jenkins server
      copy:
        src: ./itrust.xml
        dest: /tmp/itrust.xml

    - name: Creating new job for itrust
      shell: java -jar /home/jenkins-cli.jar -auth "{{username}}":"{{jenkinspassword}}" -s http://localhost:8080 create-job itrust < /tmp/itrust.xml

    - name: Installing maven
      apt: pkg=maven state=present
      become: yes


  handlers:
  - name: restart jenkins
    service: name=jenkins state=restarted
    become: yes

  - name: restart mysql
    service: name=mysql state=restarted
    become: yes
